camel.server.enabled=true
camel.server.port=8090
camel.rest.component=platform-http
camel.rest.binding-mode=off
camel.rest.port=8090
camel.rest.host=0.0.0.0

camel.component.kafka.brokers=localhost:9092

service.car=localhost:8091
service.flight=localhost:8092
service.hotel=localhost:8093

camel.opentelemetry2.enabled=true
camel.main.name=trip-booking

camel.jbang.dependencies=org.apache.camel:camel-opentelemetry2
