loggingLevel=info
loggingColor=true
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.18.0
camel.jbang.springBootVersion=3.5.10
camel.jbang.quarkusVersion=3.31.3
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusArtifactId=quarkus-bom
camel.jbang.kameletsVersion=4.17.0
camel.main.name=correlator
camel.main.routesIncludePattern=file\:traces-mapper.camel.yaml,file\:logs-mapper.camel.yaml,file\:infinispan.camel.yaml
camel.jbang.classpathFiles=kaoto-datamapper-4a94acc3.xsl,kaoto-datamapper-8f5bb2dd.xsl
camel.component.properties.location=file\:./application-dev.properties
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.18.0
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.17.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.18.0
dependency=mvn\:org.apache.activemq\:artemis-jakarta-client-all\:2.44.0
dependency=mvn\:org.messaginghub\:pooled-jms\:3.2.2
dependency=mvn\:org.apache.camel\:camel-kafka\:4.18.0
dependency=mvn\:org.apache.camel\:camel-infinispan\:4.18.0
dependency=mvn\:org.apache.camel\:camel-jms\:4.18.0
dependency=mvn\:org.apache.camel\:camel-xslt-saxon\:4.18.0
dependency=mvn\:org.apache.camel\:camel-direct\:4.18.0
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.18.0
dependency=mvn\:org.apache.camel\:camel-jsonpath\:4.18.0
dependency=mvn\:org.apache.camel\:camel-jq\:4.18.0
