loggingLevel=info
loggingColor=true
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.18.0
camel.jbang.springBootVersion=3.5.10
camel.jbang.quarkusVersion=3.31.3
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusArtifactId=quarkus-bom
camel.jbang.kameletsVersion=4.17.0
camel.main.name=ui-console
camel.main.routesIncludePattern=file\:jms-file-storage.camel.yaml,file\:rest-api.camel.yaml
camel.jbang.classpathFiles=index.html
camel.component.properties.location=file\:application-dev.properties,file\:./application-dev.properties
camel.jbang.dependencies=org.apache.camel\:camel-groovy
dependency=mvn\:org.apache.camel\:camel-groovy\:4.18.0
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.18.0
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.17.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.18.0
dependency=mvn\:org.apache.activemq\:artemis-jakarta-client-all\:2.44.0
dependency=mvn\:org.messaginghub\:pooled-jms\:3.2.2
dependency=mvn\:org.apache.camel\:camel-jms\:4.18.0
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.18.0
dependency=mvn\:org.apache.camel\:camel-file\:4.18.0
dependency=mvn\:org.apache.camel\:camel-rest\:4.18.0
dependency=mvn\:org.apache.camel\:camel-direct\:4.18.0
dependency=mvn\:org.apache.camel\:camel-jackson\:4.18.0
dependency=mvn\:org.apache.camel\:camel-platform-http\:4.18.0
