camel.server.enabled=true
camel.server.port=8093
camel.rest.component=platform-http
camel.rest.binding-mode=off
camel.rest.port=8093
camel.rest.host=0.0.0.0

camel.component.kafka.brokers=localhost:9092

camel.opentelemetry2.enabled=true
camel.main.name=hotel-booking

camel.jbang.dependencies=org.apache.camel:camel-opentelemetry2
